#!/usr/bin/env python3
"""
emit_oob.py -- division templates and starting armies for 1886.

Army size is NOT derived from the manpower placeholders in the state files.
Doing that would compound one guess with another, and it produces nonsense: the
placeholder model gives the United States 48 divisions when its actual standing
army in 1886 was about 25,000 men, smaller than Belgium's.

Instead the table below is peacetime standing strength as it actually stood in
the mid-1880s, converted at roughly 15,000 men per division. Countries not in
the table get one or two divisions by territory size, which is honest about
being a default rather than a figure.

The German Empire is the awkward case. Its army was raised by contingent: the
Prussian army absorbed most of the smaller states' forces, but Bavaria, Saxony
and Wurttemberg kept their own war ministries and general staffs right up to
1918. So the Empire's roughly 450,000 men are split by contingent rather than
handed to Prussia whole.
"""

import argparse
import collections
import os
import sys

# tag -> peacetime standing army in the mid-1880s, in thousands
ARMY = {
    "RUS": 800, "FRA": 500, "PRS": 270, "QNG": 350, "AUS": 190, "HUN": 110,
    "ITA": 250, "ENG": 200, "OTT": 150, "SPR": 100, "JAP": 70, "USA": 25,
    "COF": 120,   # alt-history: a Confederacy that survived would keep a real army
    "BAV": 50, "SXY": 32, "WUR": 18,   # the separate German contingents
    "BRA": 30, "ARG": 25, "CHL": 20, "MEX": 30, "PER": 40, "SIA": 15,
    "SWE": 40, "NOR": 18, "DEN": 15, "HOL": 25, "BEL": 45, "SWI": 30,
    "POR": 30, "GRE": 25, "ROM": 40, "SER": 20, "BUL": 30, "MTN": 10,
    "RAJ": 200,   # the Indian Army, largely sepoy
    "EGY": 15, "MOR": 20, "ETH": 60, "AFG": 40, "KOR": 15, "MHD": 50,
    "TVL": 8, "OFS": 5, "CAN": 5, "NSW": 4, "VIC": 4,
}
MEN_PER_DIVISION = 15_000

TEMPLATE = """division_template = {
\tname = "Infantry Division"
\tregiments = {
\t\tinfantry = { x = 0 y = 0 }
\t\tinfantry = { x = 0 y = 1 }
\t\tinfantry = { x = 0 y = 2 }
\t\tinfantry = { x = 1 y = 0 }
\t\tinfantry = { x = 1 y = 1 }
\t\tinfantry = { x = 1 y = 2 }
\t}
}

division_template = {
\tname = "Cavalry Division"
\tregiments = {
\t\tcavalry = { x = 0 y = 0 }
\t\tcavalry = { x = 0 y = 1 }
\t\tcavalry = { x = 1 y = 0 }
\t}
}
"""

HEADER = ("# Generated by tools/emit_oob.py\n"
          "# Division counts come from mid-1880s peacetime standing armies at\n"
          "# roughly 15,000 men per division, NOT from the manpower placeholders\n"
          "# in the state files. Countries without a researched figure get a\n"
          "# territory-based default of one or two divisions.\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--geometry", default="tools/data/state_geometry_1886.tsv")
    ap.add_argument("--mod", default="MOD")
    ap.add_argument("--pixels", default="tools/data/province_pixels.tsv")
    a = ap.parse_args()

    pix = {}
    if os.path.exists(a.pixels):
        for line in open(a.pixels, encoding="utf-8"):
            p, n = line.split()
            pix[int(p)] = int(n)

    RANK = {"megalopolis": 11, "metropolis": 10, "large_city": 9, "city": 8,
            "large_town": 7, "town": 6, "rural": 5, "pastoral": 4,
            "small_island": 3, "tiny_island": 2, "enclave": 1, "wasteland": 0}
    own = collections.defaultdict(list)
    for i, line in enumerate(open(a.geometry, encoding="utf-8")):
        if i == 0:
            continue
        f = line.rstrip("\n").split("\t")
        own[f[4].strip()].append(dict(id=int(f[0]), cat=f[3].strip(),
                                      provinces=[int(x) for x in f[5].split()]))

    d = os.path.join(a.mod, "history", "units")
    if os.path.isdir(d):
        for fn in os.listdir(d):
            if fn.endswith(".txt"):
                os.remove(os.path.join(d, fn))
    os.makedirs(d, exist_ok=True)

    researched = totdiv = 0
    for tag, states in sorted(own.items()):
        if tag in ARMY:
            n = max(1, round(ARMY[tag] * 1000 / MEN_PER_DIVISION))
            researched += 1
        else:
            provinces = sum(len(s["provinces"]) for s in states)
            n = 2 if provinces >= 40 else 1
        totdiv += n

        # spread the divisions over the country's most developed states, one
        # per state, so nothing starts as a single doomstack on the capital
        order = sorted(states, key=lambda s: (-RANK.get(s["cat"], 0), -len(s["provinces"])))
        spots = []
        while len(spots) < n:
            for s in order:
                if len(spots) >= n:
                    break
                best = max(s["provinces"], key=lambda p: pix.get(p, 0))
                spots.append(best)

        body = [HEADER, TEMPLATE, "\nunits = {\n"]
        cav = max(1, n // 6)
        for i, loc in enumerate(spots, 1):
            tpl = "Cavalry Division" if i <= cav else "Infantry Division"
            body.append("\tdivision = {\n")
            body.append(f'\t\tname = "{i}. {tpl}"\n')
            body.append(f"\t\tlocation = {loc}\n")
            body.append(f'\t\tdivision_template = "{tpl}"\n')
            body.append("\t\tstart_experience_factor = 0.2\n")
            body.append("\t}\n")
        body.append("}\n")
        with open(os.path.join(d, f"{tag}_1886.txt"), "w", encoding="utf-8") as fh:
            fh.write("".join(body))

    print(f"wrote {len(own)} order-of-battle files to {d}")
    print(f"  {researched} from researched 1880s army strengths, "
          f"{len(own) - researched} on a size default")
    print(f"  {totdiv} divisions worldwide")
    return 0


if __name__ == "__main__":
    sys.exit(main())
