#!/usr/bin/env python3
"""
emit_supplyareas.py -- supply areas consistent with the mod's own states.

This is what made the game refuse to load the map.

The mod defines its own history/states but inherits vanilla's map/, and
map/supplyareas is part of the map. Hearts of Iron IV requires every state to
belong to exactly one supply area, and every supply area to name only states
that exist. Neither held:

  - The mod creates 57 states by splitting vanilla ones -- Germany into its 26
    members, the Balkans, Laos -- with ids above 800. Vanilla's supply areas
    cannot possibly reference them.
  - The mod drops 12 vanilla state ids that ended up with no territory, and
    vanilla's supply areas still name them.

Both are broken references in the map definition, which is exactly what the
game reported.

The grouping is recovered from the previous mod's supply areas rather than
invented: they already assign every one of this mod's 857 states to an area.
References to states this mod does not define are dropped, and any area left
with no states at all is not emitted.
"""

import argparse
import collections
import os
import re
import sys

ID = re.compile(r"\bid\s*=\s*(\d+)")
NAME = re.compile(r'name\s*=\s*"([^"]*)"')
VALUE = re.compile(r"\bvalue\s*=\s*(\d+)")
STATES = re.compile(r"states\s*=\s*\{([^}]*)\}", re.S)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", required=True, help="reference supplyareas directory")
    ap.add_argument("--geometry", default="tools/data/state_geometry_1886.tsv")
    ap.add_argument("--mod", default="MOD")
    a = ap.parse_args()

    mine = set()
    for i, line in enumerate(open(a.geometry, encoding="utf-8")):
        if i:
            mine.add(int(line.split("\t")[0]))

    areas = {}
    seen = collections.Counter()
    for fn in sorted(os.listdir(a.source)):
        if not fn.endswith(".txt"):
            continue
        t = open(os.path.join(a.source, fn), encoding="utf-8", errors="replace").read()
        m = ID.search(t)
        if not m:
            continue
        aid = int(m.group(1))
        nm = NAME.search(t)
        v = VALUE.search(t)
        keep = []
        for blk in STATES.findall(t):
            for x in blk.split():
                if x.isdigit() and int(x) in mine:
                    keep.append(int(x))
                    seen[int(x)] += 1
        areas[aid] = dict(id=aid,
                          name=nm.group(1) if nm else f"SUPPLYAREA_{aid}",
                          value=int(v.group(1)) if v else 3,
                          states=sorted(set(keep)))

    dupes = [s for s, n in seen.items() if n > 1]
    missing = sorted(mine - set(seen))
    if dupes:
        print(f"FAIL: {len(dupes)} states named by more than one supply area: {dupes[:10]}")
        return 1
    if missing:
        print(f"FAIL: {len(missing)} states in no supply area: {missing[:10]}")
        return 1

    d = os.path.join(a.mod, "map", "supplyareas")
    if os.path.isdir(d):
        for fn in os.listdir(d):
            if fn.endswith(".txt"):
                os.remove(os.path.join(d, fn))
    os.makedirs(d, exist_ok=True)

    written = dropped = 0
    for aid, ar in sorted(areas.items()):
        if not ar["states"]:
            dropped += 1
            continue
        body = [
            "# Generated by tools/emit_supplyareas.py\n",
            "# Every state this mod defines is in exactly one supply area, and no\n",
            "# area names a state the mod does not define. The game refuses to load\n",
            "# the map if either does not hold.\n",
            "supply_area = {\n",
            f"\tid = {ar['id']}\n",
            f'\tname = "{ar["name"]}"\n',
            f"\tvalue = {ar['value']}\n",
            "\tstates = {\n\t\t",
            " ".join(str(s) for s in ar["states"]),
            "\n\t}\n}\n",
        ]
        with open(os.path.join(d, f"{aid}-SupplyArea.txt"), "w", encoding="utf-8") as fh:
            fh.write("".join(body))
        written += 1

    print(f"wrote {written} supply areas to {d}")
    print(f"  {len(mine)} states, each in exactly one area")
    print(f"  {dropped} source areas dropped for having no states left")
    return 0


if __name__ == "__main__":
    sys.exit(main())
