#!/usr/bin/env python3
"""
emit_states.py -- write MOD/history/states/*.txt from the 1886 geometry table.

The geometry table settles which provinces belong to which state and who owns
each state. This turns that into the files the game reads.

Two things are worth knowing about the output.

**The mod replaces vanilla's states entirely** rather than overriding them file
by file. Hearts of Iron IV merges history/states by filename, so a mod file
called 1886-Bavaria.txt does not replace vanilla's 50-Wurttemberg.txt -- both
load, and the state id is then defined twice. That is precisely the failure that
left the previous mod with 65 duplicate state ids. Declaring
replace_path="history/states" makes the game ignore vanilla's directory
altogether, so filenames stop mattering and a duplicate becomes impossible.

**Manpower, infrastructure and victory points are placeholders.** The geometry
and ownership are researched; these are not. They are derived from each state's
category on a single scale, chosen to be plausible for 1886 -- roughly a third
of vanilla's 1936 figures, since world population was about a third lower and
industry far more concentrated. They are marked as such in every file so nobody
mistakes them for research.
"""

import argparse
import collections
import os
import re
import sys

# state_category -> (manpower, infrastructure, victory points)
# Deliberately conservative: 1886, not 1936.
PROFILE = {
    "wasteland":    (0,        0, 0),
    "enclave":      (5_000,    1, 0),
    "tiny_island":  (8_000,    1, 0),
    "small_island": (20_000,   1, 0),
    "pastoral":     (30_000,   1, 0),
    "rural":        (70_000,   1, 0),
    "town":         (160_000,  2, 1),
    "large_town":   (320_000,  2, 3),
    "city":         (650_000,  3, 5),
    "large_city":   (1_100_000, 3, 8),
    "metropolis":   (1_900_000, 4, 12),
    "megalopolis":  (3_200_000, 5, 20),
}

HEADER = ("# Generated by tools/emit_states.py from tools/data/state_geometry_1886.tsv\n"
          "# Edit the region tables under tools/regions/, not this file.\n"
          "# Provinces and owner are researched. Manpower, infrastructure and\n"
          "# victory points are category-derived placeholders for 1886.\n")


def safe(name):
    keep = "".join(c if (c.isalnum() or c in " -()") else "" for c in name)
    return re.sub(r"\s+", "_", keep.strip())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--geometry", default="tools/data/state_geometry_1886.tsv")
    ap.add_argument("--mod", default="MOD")
    ap.add_argument("--largest", default="tools/data/province_pixels.tsv",
                    help="province id -> pixel count, for placing victory points")
    a = ap.parse_args()

    pixels = {}
    if os.path.exists(a.largest):
        for line in open(a.largest, encoding="utf-8"):
            p, n = line.split()
            pixels[int(p)] = int(n)

    rows = []
    for i, line in enumerate(open(a.geometry, encoding="utf-8")):
        if i == 0:
            continue
        f = line.rstrip("\n").split("\t")
        sid, key, name, cat, owner, provs = f[:6]
        rows.append(dict(id=int(sid), key=key, name=name.strip(), category=cat,
                         owner=owner, provinces=[int(x) for x in provs.split()]))

    d = os.path.join(a.mod, "history", "states")
    if os.path.isdir(d):
        for fn in os.listdir(d):
            if fn.endswith(".txt"):
                os.remove(os.path.join(d, fn))
    os.makedirs(d, exist_ok=True)

    unknown = collections.Counter()
    loc = []
    for r in rows:
        cat = r["category"] if r["category"] in PROFILE else "rural"
        if r["category"] not in PROFILE:
            unknown[r["category"]] += 1
        mp, infra, vp = PROFILE[cat]
        # the victory point goes on the state's physically largest province
        best = max(r["provinces"], key=lambda p: pixels.get(p, 0)) if r["provinces"] else None

        body = [HEADER, "state = {\n"]
        body.append(f"\tid = {r['id']}\n")
        body.append(f"\tname = \"STATE_{r['id']}\"\n")
        body.append(f"\tmanpower = {mp}\n")
        body.append(f"\tstate_category = {cat}\n\n")
        body.append("\thistory = {\n")
        body.append(f"\t\towner = {r['owner']}\n")
        body.append(f"\t\tadd_core_of = {r['owner']}\n")
        if vp and best is not None:
            body.append(f"\t\tvictory_points = {{ {best} {vp} }}\n")
        body.append("\t\tbuildings = {\n")
        body.append(f"\t\t\tinfrastructure = {infra}\n")
        body.append("\t\t}\n")
        body.append("\t}\n\n")
        body.append("\tprovinces = {\n\t\t")
        body.append(" ".join(str(p) for p in r["provinces"]))
        body.append("\n\t}\n")
        body.append("}\n")

        fn = f"{r['id']}-{safe(r['name'])}.txt"
        with open(os.path.join(d, fn), "w", encoding="utf-8") as fh:
            fh.write("".join(body))
        loc.append((r["id"], r["name"]))

    lp = os.path.join(a.mod, "localisation", "states_1886_l_english.yml")
    os.makedirs(os.path.dirname(lp), exist_ok=True)
    with open(lp, "w", encoding="utf-8-sig") as fh:
        fh.write("l_english:\n")
        for sid, name in sorted(loc):
            fh.write(f' STATE_{sid}:0 "{name}"\n')

    print(f"wrote {len(rows)} state files to {d}")
    print(f"wrote {len(loc)} state names to {lp}")
    if unknown:
        print(f"  categories not in the profile table, defaulted to rural: {dict(unknown)}")
    tot = sum(len(r["provinces"]) for r in rows)
    print(f"  {tot} provinces, {len(set(r['owner'] for r in rows))} owners")
    return 0


if __name__ == "__main__":
    sys.exit(main())
