#!/usr/bin/env python3
"""
emit_countries.py -- write MOD/history/countries/*.txt for every country that
owns territory in 1886.

Like the states, this replaces vanilla's directory rather than overriding it
file by file. Vanilla's country files set up 1936 politics, technology and
armies for countries that in 1886 either did not exist or looked nothing alike,
and leaving them to load alongside would mean the Third Republic being handed
the Popular Front's cabinet.

## Ideologies: vanilla's, deliberately

A mod set in 1886 wants Victorian ideologies -- absolutism, liberalism,
socialism, and so on -- not democratic/fascism/communism/neutrality. It does not
get them here, on purpose.

Replacing common/ideologies means every vanilla idea, focus and event that
references a vanilla ideology stops resolving. An earlier attempt at exactly
that in the previous mod took the error count from about 51,000 to 211,000. A
Victorian ideology set is a real piece of design work that has to be done
together with the ideas and focus trees that depend on it; doing it now, before
the mod has ever booted, would trade a working map for a broken one.

So each country is mapped onto vanilla's four: parliamentary and republican
states to `democratic`, everything else -- absolute monarchies, empires,
sultanates, khanates and chartered companies alike -- to `neutrality`, which is
vanilla's non-aligned catch-all. Nothing is `fascism` or `communism`, neither of
which exists in 1886.

## Capitals

Chosen as the highest-category state a country owns, which is right for most of
them -- Prussia lands on Brandenburg, France on Ile de France, Britain on
Greater London. Where the heuristic picks a rich province over the actual seat
of government it is overridden by name below, with the reason.
"""

import argparse
import collections
import os
import sys

RANK = {"megalopolis": 11, "metropolis": 10, "large_city": 9, "city": 8,
        "large_town": 7, "town": 6, "rural": 5, "pastoral": 4,
        "small_island": 3, "tiny_island": 2, "enclave": 1, "wasteland": 0}

# Parliamentary or republican in 1886. Everything else is neutrality.
DEMOCRATIC = {
    "FRA", "USA", "COF", "CAL", "TEX", "CDA", "DES", "AZT", "SWI", "HOL", "BEL",
    "ENG", "NOR", "SWE", "DEN", "POR", "SPR", "ITA", "GRE", "CAN", "NZL",
    "NSW", "VIC", "QLD", "SAS", "WAU", "TAS", "LIB", "OFS", "TVL", "MEX",
    "BRA", "ARG", "CHL", "URG", "PRU", "BOL", "VEN", "COL", "PAR", "ECU",
    "DOM", "HAI", "NIC", "GUA", "HON", "COS", "ELS", "HAW", "SMA", "SRW",
}

# Where the highest-category state is not the seat of government.
CAPITAL = {
    "RUS": 195,  # Sankt Petersburg, not Moscow: the court moves back only in 1918
    "QNG": 608,  # Beijing, not Shanghai
    "OTT": 184,  # Constantinople, in the Thrace state, not Adrianople
    "SPR": 41,   # Madrid, not Catalonia
    "SWE": 141,  # Stockholm, in Svealand
    "ITA": 2,    # Rome, in Lazio, not Piedmont -- the capital moved in 1871
    "HUN": 155,  # Budapest, in Transdanubia
    "ARG": 509,  # Buenos Aires
    "BAV": 52,   # Munich, in Upper Bavaria, not the detached Rhenish Palatinate
    "KOR": 525,  # Seoul, not Pyongyang
    "USA": 361,  # Washington, in Maryland, not New York
    "NZL": 284, "NSW": 285, "VIC": 517, "TAS": 518, "WAU": 522,
}

HEADER = ("# Generated by tools/emit_countries.py\n"
          "# Capital and government come from the 1886 state table and the maps in\n"
          "# that script. Technology, research slots and stability are placeholders.\n"
          "# The order of battle is in history/units/<TAG>_1886.txt.\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--geometry", default="tools/data/state_geometry_1886.tsv")
    ap.add_argument("--mod", default="MOD")
    a = ap.parse_args()

    own = collections.defaultdict(list)
    names = {}
    for i, line in enumerate(open(a.geometry, encoding="utf-8")):
        if i == 0:
            continue
        f = line.rstrip("\n").split("\t")
        sid, key, name, cat, owner, provs = f[:6]
        own[owner.strip()].append(dict(id=int(sid), category=cat.strip(),
                                       n=len(provs.split()), name=name.strip()))
        names[int(sid)] = name.strip()

    # country display names, from the generated tag file
    disp = {}
    tagfile = os.path.join(a.mod, "common", "country_tags", "00_countries.txt")
    if os.path.exists(tagfile):
        for line in open(tagfile, encoding="utf-8"):
            if "#" in line and "=" in line:
                tag = line.split("=")[0].strip()
                disp[tag] = line.split("#", 1)[1].strip()

    d = os.path.join(a.mod, "history", "countries")
    if os.path.isdir(d):
        for fn in os.listdir(d):
            if fn.endswith(".txt"):
                os.remove(os.path.join(d, fn))
    os.makedirs(d, exist_ok=True)

    errs = []
    written = 0
    for tag, states in sorted(own.items()):
        cap = CAPITAL.get(tag)
        if cap is not None and not any(s["id"] == cap for s in states):
            errs.append(f"{tag}: override capital {cap} ({names.get(cap,'?')}) "
                        f"is not a state {tag} owns")
            cap = None
        if cap is None:
            cap = max(states, key=lambda s: (RANK.get(s["category"], 0), s["n"]))["id"]

        gov = "democratic" if tag in DEMOCRATIC else "neutrality"
        body = [HEADER, f"capital = {cap}\n\n"]
        body.append(f'oob = "{tag}_1886"\n\n')
        body.append("set_research_slots = 2\n")
        body.append("set_stability = 0.6\n")
        body.append("set_war_support = 0.4\n\n")
        body.append("set_politics = {\n")
        body.append(f"\truling_party = {gov}\n")
        body.append("\tlast_election = \"1885.1.1\"\n")
        body.append(f"\tis_elections_allowed = {'yes' if gov == 'democratic' else 'no'}\n")
        body.append("}\n\n")
        body.append("set_popularities = {\n")
        if gov == "democratic":
            body.append("\tdemocratic = 70\n\tneutrality = 30\n")
        else:
            body.append("\tneutrality = 70\n\tdemocratic = 30\n")
        body.append("}\n")

        name = disp.get(tag, tag)
        safe = "".join(c if (c.isalnum() or c in " -") else "" for c in name).strip()
        with open(os.path.join(d, f"{tag} - {safe}.txt"), "w", encoding="utf-8") as fh:
            fh.write("".join(body))
        written += 1

    for e in errs:
        print("FAIL:", e)
    if errs:
        return 1
    dem = sum(1 for t in own if t in DEMOCRATIC)
    print(f"wrote {written} country files to {d}")
    print(f"  {dem} democratic, {written - dem} neutrality")
    print(f"  capitals: {len(CAPITAL)} overridden by name, "
          f"{written - len(CAPITAL)} chosen by state category")
    return 0


if __name__ == "__main__":
    sys.exit(main())
